name: my_budget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  intl: ^0.20.2
  sqflite: ^2.4.1
  syncfusion_flutter_datepicker: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
