name: my_budget
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  device_frame_plus: ^1.5.0
  drift: ^2.28.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^9.7.0
  font_awesome_flutter: ^10.8.0
  form_builder_validators: ^11.1.2
  get_it: ^8.2.0
  go_router: ^16.0.0
  intl: any
  path: ^1.9.0
  path_provider: ^2.1.5
  pie_chart: ^5.4.0
  provider: ^6.1.5
  sqflite: ^2.4.1
  sqlite3_flutter_libs: ^0.5.38
  syncfusion_flutter_datepicker: ^29.1.38
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
    - lib/assets/translations/
